# Setup a cache to cache job parts between jobs to ensure faster builds
cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - $HOME/.cargo/
    - target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: "FULL"
  GIT_SUBMODULE_STRATEGY: recursive

image: rust:latest

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    # Install dependencies to build
    # `clang` is necessary for `setjmp`
    - apt-get update -qy
    - apt-get install -y clang
    - apt-get clean
    # Trigger installation
    - rustc --version

check:
  stage: test
  before_script:
    # Install dependencies to build
    # `clang` is necessary for `setjmp`
    - apt-get update -qy
    - apt-get install -y clang
    - apt-get clean
    - rustup component add rustfmt clippy
    - cargo install cargo-audit
  script:
    - cargo check --verbose
    - cargo fmt -- --check
    - cargo clippy -p hp-brcu -- -D warnings
    - cargo audit

    # Note: Using `-p` flag to individually test `hp-brcu` doesn't work,
    # because `hp-brcu` requires dev-dependencies.
    - cd hp-brcu
    - cargo test -- --nocapture
    - cargo test --release -- --nocapture
    - cd ..

    - cargo test -- --nocapture --test-threads 1
    - cargo test --release -- --nocapture --test-threads 1

pages:
  stage: deploy
  before_script:
    # Install dependencies to build
    # `clang` is necessary for `setjmp`
    - apt-get update -qy
    - apt-get install -y clang
    - apt-get clean
  script:
    - cargo doc
    - mkdir -p public && cp -r target/doc/* public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
