[package]
name = "pebr-benchmark"
version = "0.1.0"
authors = ["Jerry Jaehwang Jung <tomtomjhj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "0.7.1"
crossbeam-utils = "0.6.5"
rand = "0.7"
