[package]
name = "pebr-benchmark"
version = "0.1.0"
authors = ["authors"]
edition = "2018"

[dependencies]
bitflags = "1.0"
cfg-if = "0.1"
clap = "2.33.0"
crossbeam-utils = "0.6.5"
csv = "1.1.1"
jemallocator = "0.3"
jemalloc-ctl = "0.3"
rand = "0.7"
typenum = "1.10"

[dependencies.crossbeam-ebr]
package = "crossbeam-epoch"
path = "crossbeam-ebr/crossbeam-epoch"

[dependencies.crossbeam-pebr]
package = "crossbeam-pebr-epoch"
path = "crossbeam-pebr/crossbeam-epoch"

# TODO: remove this
[profile.release]
debug = true

[features]
sanitize = ["crossbeam-pebr/sanitize"]
