[package]
name = "pebr-benchmark"
version = "0.1.0"
authors = ["Jaehwang Jung <jaehwang.jung@kaist.ac.kr>", "Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
clap = "2.33.0"
crossbeam-utils = "0.6.5"
csv = "1.1.1"
jemallocator = "0.3"
rand = "0.7"
typenum = "1.10"

# crossbeam-epoch = "0.7.1"
[dependencies.crossbeam-ebr]
package = "crossbeam-epoch"
path = "crossbeam-ebr/crossbeam-epoch"

[dependencies.crossbeam-pebr]
package = "crossbeam-pebr-epoch"
path = "crossbeam-pebr/crossbeam-epoch"

[profile.release]
debug = true

[features]
profiling = ['jemallocator/profiling']
