[package]
name = "smr-benchmark"
version = "0.1.0"
authors = ["authors"]
edition = "2021"
default-run = "smr-benchmark"

[dependencies]
bitflags = "2.3"
cfg-if = "1.0"
clap = { version = "4.3.8", features = ["derive"] }
crossbeam-utils = { path = "./crossbeam-ebr/crossbeam-utils" }
csv = "1.2.2"
rand = "0.8"
typenum = "1.16"
num = "0.4.1"
hp_pp = { path = "./hp_pp" }
nbr-rs = { path = "./nbr-rs" }
cdrc-rs = { path = "./cdrc-rs" }
hp-sharp = { path = "./hp-sharp" }
vbr-rs = { path = "./vbr-rs" }
circ = { path = "./circ" }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = "0.5"
tikv-jemalloc-ctl = "0.5"

[dependencies.crossbeam-ebr]
package = "crossbeam-epoch"
path = "crossbeam-ebr/crossbeam-epoch"

[dependencies.crossbeam-pebr]
package = "crossbeam-pebr-epoch"
path = "crossbeam-pebr/crossbeam-epoch"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release-simple]
inherits = "release"
debug = true
lto = false
codegen-units = 16

[features]
sanitize = ["crossbeam-pebr/sanitize"]
